CREATE TABLE tv_serie (
	id					UUID			NOT NULL,
	tv_series_id		UUID			NOT NULL,
	provider_id			VARCHAR			NOT NULL,
	name				VARCHAR					,
	language			VARCHAR(2)		NOT NULL,
	first_aired			DATE					,
	content_rating		VARCHAR(5)				,
	network				VARCHAR					,
	overview			CLOB					,
	rating				VARCHAR(4)				,
	rating_count		VARCHAR					,
	status				VARCHAR(10)				,
	banner				VARCHAR					,
	fanart				VARCHAR					,
	poster				VARCHAR					,
	imdb_id				VARCHAR(10)				,
	PRIMARY KEY (id),
	CONSTRAINT tv_serie_fk FOREIGN KEY (tv_series_id) REFERENCES tv_series(id) ON DELETE CASCADE
);
